### ISSUE TITLE
Check the current nodejs tutorials can deal with GitPod

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#124]
The current node tutorial works with Gitpod, but the Jenkinsfile tells us to check HTTP://localhost:3000, which can't work for Gitpod.

We should modify the documentation to take this into account, or modify the Jenkinsfile dynamically as a workaround.

**Comment by ash-sxn** [comment]
Jenkinsfile will be created by the user, so we'll have to update the documentation dynamically which could cause confusion to the user. 
We could use `gitpodURL.sh` to give the URL for this, but that would require the user to run the `gitpodURL.sh` script manually in gitpod while running the tutorial in Jenkins 
another solution is that we ask the user to change the URL's `8080` to `3000` to view it (we can update the Jenkinsfile for this)
