### ISSUE TITLE
Add Guidelines to Run Example 01 in Gitpod

### ISSUE THREAD

**Issue by berviantoleo** [ash-sxn/GSoC-2023-docker-based-quickstart#13]
Please add guidelines to run example 01 in Gitpod. 

Please cover these sections:

* How to set up the repo in Gitpod?
* Steps to run example 01
* How to verify Jenkins was installed?

You can add other sections that would be helpful.

The guidelines will help me to learn Gitpod and how to run your example. Feel free to ask if you have any questions.

**Comment by ash-sxn** [comment]
OK, I'll add these sections today

but what do you mean by "How to verify?"?

**Comment by berviantoleo** [comment]
> OK, I'll add these sections today
> 
> but what do you mean by "How to verify?"?

Updated the description, I want to verify the setup process is finished.

**Comment by ash-sxn** [comment]
Ok
thank you @berviantoleo 
I'll add them
