### ISSUE TITLE
Dependabot is not configured yet

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#153]
![image](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/assets/116569/87dffa6f-f4de-4af4-9aa0-7074f4534a4c)

**Comment by gounthar** [comment]
The dependabot.yml already exists, but there are still things to configure in GitHub settings.

**Comment by berviantoleo** [comment]
> The dependabot.yml already exists, but there are still things to configure in GitHub settings.

I just realized that. 😅 Thanks. Need @ash-sxn to enable the Dependabot.

**Comment by berviantoleo** [comment]
Dependabot can't be enabled in my fork. Not sure why. I've clicked the button, and it keeps disabled.

![dependabot](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/assets/15927349/d65bf8e9-60c8-4e50-88dc-eecf21d48963)

**Comment by gounthar** [comment]
Ashutosh's error is not the same, all Dependabot settings are enabled, but the Dependabot action never gets fired. 🤔 
You can't get it enabled, Ashutosh can't get it to work, and my fork is the only repo where Dependabot works. 😢 

I will try to understand more about that.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors

**Comment by gounthar** [comment]
We're not alone: https://github.com/dependabot/dependabot-core/issues/2306 .

**Comment by gounthar** [comment]
Solved by removing duplicate sections.
