### ISSUE TITLE
Use conventional commits approach

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#17]
The "Conventional Commits" approach suggests using specific prefixes in commit messages to convey the nature of the changes made. Here are the common prefixes used:

- **feat**: Used for new features or enhancements.
- **fix**: Used for bug fixes.
- **chore**: Used for maintenance tasks, build processes or other non-user-facing changes.
- **docs**: Used for documentation-related changes.
- **style**: Used for code style changes (e.g., formatting, indentation).
- **refactor**: Used for code refactoring, without adding new features or fixing bugs.
- **test**: Used for adding or modifying tests.
- **perf**: Used for performance-related improvements.
- **build**: Used for changes related to the build system or external dependencies.
- **ci**: Used for changes to the continuous integration (CI) configuration or scripts.

Using these prefixes helps provide a clear and standardized way to categorize and understand the purpose of each commit.
It improves the readability and maintainability of commit history, making it easier for others (including your future self) to comprehend the changes made in the codebase.

It's important to note that while the Conventional Commits approach is widely used and considered good practice, it's not mandatory. 
The key is to write descriptive and meaningful commit messages that accurately convey the purpose and impact of each commit.

**Comment by ash-sxn** [comment]
Thank you @gounthar 
for mentioning this. I'll remember in future to use the convention 
Is there a convention for naming Branches too?

**Comment by gounthar** [comment]
When it comes to naming branches, there are a few conventions and best practices that can help make your branch names more descriptive and organized.
It greatly varies depending on the project, and I'm not sure it's clearly defined for the Jenkins project.
Anyway, here are some common guidelines:

- Use descriptive names: Choose branch names that clearly describe the purpose or goal of the branch. A well-named branch makes it easier for others (including your future self) to understand its purpose.
- Use hyphens or underscores: Separate words in the branch name using hyphens ("-") or underscores ("_") to improve readability. For example, **`feature/new-feature`** or **`bugfix/issue-123**`.
- Prefix with a category: Consider prefixing your branch names with a category or type to indicate the nature of the changes. Some commonly used prefixes include:
  - **`feature/`**: Used for new feature development.
  - **`bugfix/`**: Used for bug fixes.
  - **`hotfix/`**: Used for critical bug fixes in production.
  - **`refactor/`**: Used for refactoring code without adding new features or fixing bugs.
  - **`chore/`**: Used for maintenance tasks or non-user-facing changes.
  - **`docs/`**: Used for documentation-related changes.
  - **`test/`**: Used for adding or modifying tests.
- Include a reference ID (optional): as we're using GitHub's issues, you may consider including an issue number in the branch name to associate it with a specific task or issue. For example, **`feature/issue-123`**.
- Keep it concise: Aim for concise branch names that convey the necessary information without being too lengthy.
Long branch names can be cumbersome to work with.

Here's an example that combines these conventions:
```
feature/add-login-functionality
bugfix/fix-navigation-bug
refactor/restructure-database-schema
chore/update-dependencies
docs/update-readme
test/add-unit-tests
```

Remember, these conventions are not strict rules, but rather guidelines to help maintain consistency and clarity within this project. I even can't promise I will follow these rules every time. 🤣

**Comment by ash-sxn** [comment]
Thankyou @gounthar 
I'll remember to use these in future

**Comment by gounthar** [comment]
Thanks.
It's not mandatory, but it's a nice plus. 🤷

**Comment by ash-sxn** [comment]
Should we close this issue now?

**Comment by gounthar** [comment]
A very informative video about `git`, just in case: https://www.youtube.com/watch?v=Uszj_k0DGsg
