### ISSUE TITLE
(bug) remove configuration warning (hostname)

### ISSUE THREAD

**Issue by jmMeessen** [ash-sxn/GSoC-2023-docker-based-quickstart#34]
Remove the configuration warning `Jenkins URL is empty but is required for the proper operation of many Jenkins features like email notifications, PR status update, and environment variables such as BUILD_URL.`

**Comment by ash-sxn** [comment]
What do I put as the URL? controller container name?

**Comment by berviantoleo** [comment]
I think `localhost` should be fine. What do you think @jmMeessen?

**Comment by jmMeessen** [comment]
It's been some time I did it and I don't trust my memory.
It is not critical, functionally, but the warning is very untidy.

**Comment by ash-sxn** [comment]
> I think `localhost` should be fine. What do you think @jmMeessen?

It's saying this with localhost `Please set a valid host name, instead of localhost`

**Comment by ash-sxn** [comment]
> It's been some time I did it and I don't trust my memory. It is not critical, functionally, but the warning is very untidy.

Warning is not coming anymore since I've added container name right now, but I don't know if all the things it says are working or not `email notifications, PR status update, and environment variables such as BUILD_URL.`
