### ISSUE TITLE
feature(Tutorial 3): Build a Node.js and React app with npm  

### ISSUE THREAD

**Issue by ash-sxn** [ash-sxn/GSoC-2023-docker-based-quickstart#40]
- For discussion to replicate Tutorial [Build a Node.js and React app with npm](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/)
- Uses  docker in docker 
- Pinging mentors @berviantoleo @gounthar @jmMeessen

**Comment by gounthar** [comment]
See #69.
