### ISSUE TITLE
feature(Tutorial 4): Build a Python app with PyInstaller  

### ISSUE THREAD

**Issue by ash-sxn** [ash-sxn/GSoC-2023-docker-based-quickstart#41]
- For discussion to replicate Tutorial [Build a Python app with PyInstaller](https://www.jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/)
- Does not use docker in docker
- Pinging mentors @berviantoleo @gounthar @jmMeessen

**Comment by gounthar** [comment]
See #65

**Comment by gounthar** [comment]
It should also use the GitHub action to be tested.

**Comment by gounthar** [comment]
Will close when #117 will be done.
