### ISSUE TITLE
Use the key generation script in the Dockerfile

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#44]
For the time being, you are not creating keys in the Dockerfile, but in a separate step (hopefully before launching the whole system thanks to docker `compose up --build`.
I think calling the key-creation script within the Dockerfile could be helpful.

**Comment by jmMeessen** [comment]
I am not sure that this will work (worth experimenting) @gounthar 
As far as I know, the public key of the generated key pair must be set in the compose file itself ("upstream" configuration compared to the dockerfile).

Interested to hear @ash-sxn experimentation results.

**Comment by gounthar** [comment]
You're right, that's flawed by design. 🤦

**Comment by jmMeessen** [comment]
We are going to park this proposal.
