### ISSUE TITLE
(bug) SSH-Key generation: git work-tree is left "dirty" when executing the key generation script

### ISSUE THREAD

**Issue by jmMeessen** [ash-sxn/GSoC-2023-docker-based-quickstart#48]
Ref PR #42 

When the key generation script is executed, the compose file and keys are seen as git changes (dirty git worktree)

**Comment by gounthar** [comment]
Is there any quick hint you'd like to share?
Thanks.

**Comment by gounthar** [comment]
More information gathered from our last weekly meeting:

Will this disturb the first persona?
When we generate the SSH key locally, the `docker-compose` file is modified, resulting in the creation of two new files. This might provide the user with disturbing information. To address this, we can consider manipulating the `.gitignore` file to ignore the `secrets` directory. For `docker-compose`, we can use a template, make a copy of it, modify it as needed, and delete it after executing the teardown command. Additionally, we can add it to the `.gitignore` file.

**Comment by ash-sxn** [comment]
what about adding  `git restore docker-compose.yaml` in the teardown command to solve for docker-compose file ?

**Comment by gounthar** [comment]
That would be a quick workaround, but would not solve the issue.
It's worth implementing though.
We will have another look after the midterm to find the correct solution.
