### ISSUE TITLE
Single "up" and "down" commands to setup/start and tear down environment

### ISSUE THREAD

**Issue by jmMeessen** [ash-sxn/GSoC-2023-docker-based-quickstart#49]
Based on the experiences, and as suggested in PR conversations, it is best to have a single command to setup and start the environment. (and tear it down)

See comment https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/pull/42#pullrequestreview-1492791293

**Comment by gounthar** [comment]
- Utilize a single-point script/entry point (that does everything for every tutorial) whenever possible.
- Use a minimal set of scripts when distinct steps are mandatory, such as when the user needs to interact with GitHub or Jenkins before proceeding to the next step.
